FROM oven/bun:1

WORKDIR /usr/src/app

COPY . .

RUN bun install

RUN bunx turbo build --filter=backend...
RUN bun run generate:db

EXPOSE 8080

# Start the frontend application
CMD ["bun", "start:backend"]
